import { chromium } from '@playwright/test';
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || undefined });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
const page = await ctx.newPage();
await page.goto('http://localhost:4173/', { waitUntil: 'networkidle' });
await page.keyboard.press('Escape').catch(() => {});
await page.waitForTimeout(1200);
await page.locator('button', { hasText: /ColoZoo/ }).last().click({ force: true });
await page.locator('img[alt="colozoo"]').waitFor({ timeout: 8000 });
await page.waitForTimeout(1500);
await page.getByRole('button', { name: 'Brushes' }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/cz-panel-brush.png' });
await page.getByRole('button', { name: 'Colors' }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/cz-panel-colors.png' });
await page.getByRole('button', { name: 'Coloring books' }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/cz-panel-books.png' });
console.log('panel shots done');
await browser.close();
